<?php

declare(strict_types=1);

namespace Kindharika\ApiStarter\Base;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Http\FormRequest;

/**
 * Contract for CRUD + datatable services generated by api:scaffold / module:scaffold.
 */
interface BaseServiceInterface
{
    /**
     * Paginated datatable listing.
     *
     * Expected filter keys (from query string):
     * - entries (int): per page
     * - search_key (string), search_columns (csv string)
     * - sort_column (string), sort_type ("asc"|"desc")
     * - filter_columns (csv), filter_keys (csv, use "|" for whereIn, "null" for whereNull)
     * - filter_date_column, filter_date_start, filter_date_end
     *
     * @param  array<string, mixed>|FormRequest|mixed  $filter
     * @return LengthAwarePaginator<int, Model>
     */
    public function dataTable(mixed $filter): mixed;

    /**
     * Fetch one record by primary key (UUID string by default).
     *
     * @param  string|int  $id
     * @return Model
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function getById(mixed $id): mixed;

    /**
     * Create a record from FormRequest or associative array.
     *
     * @param  FormRequest|array<string, mixed>|mixed  $data
     * @return Model
     */
    public function create(mixed $data): mixed;

    /**
     * Update a record by id.
     *
     * @param  string|int  $id
     * @param  FormRequest|array<string, mixed>|mixed  $data
     * @return Model
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function update(mixed $id, mixed $data): mixed;

    /**
     * Soft-delete (BaseModel) a record by id; returns the deleted model instance.
     *
     * @param  string|int  $id
     * @return Model
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function delete(mixed $id): mixed;
}
